language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
install:
  - brew install watchman
  - npm install
before_script:
  - npm test
  - (npm start > packager.log 2>&1 &) && echo $! > packager.pid

after_script:
  - pkill -9 -F packager.pid
  - cat packager.log
  - rm packager.log
  - rm packager.pid

# Automatically publish the website
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = false ] && [ "$TRAVIS_BRANCH" = master ]; then
    echo "machine github.com login reactjs-bot password $GITHUB_TOKEN" >~/.netrc
    cd website
    npm install
    ./setup.sh
    ./publish.sh
  fi

env:
  global:
    - secure: "HlmG8M2DmBUSBh6KH1yVIe/8gR4iibg4WfcHq1x/xYQxGbvleq7NOo04V6eFHnl9cvZCu+PKH0841WLnGR7c4BBf47GVu/o16nXzggPumHKy++lDzxFPlJ1faMDfjg/5vjbAxRUe7D3y98hQSeGHH4tedc8LvTaFLVu7iiGqvjU="

branches:
  only:
    - master
