name: 🐛 Bug Report
description: Report a reproducible bug or regression in React Native.
labels: ["Needs: Triage :mag:"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the information requested. Issues that do not follow this format are likely to stall.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is. Include screenshots if needed. Test using the [latest React Native release](https://github.com/facebook/react-native/releases/latest) to make sure your issue has not already been fixed.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: React Native Version
      description: What is the latest version of react-native that this issue reproduces on? Please only list the highest version you tested. Bear in mind that only issues on [supported versions](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) will be looked into.
      placeholder: ex. 0.71.0
    validations:
      required: true
  - type: textarea
    id: react-native-info
    attributes:
      label: Output of `npx react-native info`
      description: Run `npx react-native info` in your terminal, copy and paste the results here.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Snack, screenshot, or link to a repository
      description: |
        Please provide a Snack (https://snack.expo.dev/), a link to a repository on GitHub that reproduces the problem.
        You may provide a screenshot of the application if you think it is relevant to your bug report.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
        Please note that a reproducer is **mandatory**. Issues without reproducer are more likely to stall and will be closed.
    validations:
      required: true
