  tests_e2e:
    when:
      and:
        - equal: [ false, << pipeline.parameters.run_release_workflow >> ]
        - equal: [ false, << pipeline.parameters.run_nightly_workflow >> ]
    jobs:
      - test_e2e_ios:
          ruby_version: "2.7.7"
      - test_e2e_android
