name: Create new tag as version label

on:
  release:
    types:
      - created
      - edited

jobs:
  add-new-tag-version-label:
    runs-on: ubuntu-latest

    steps:
      - uses: lucasbento/core-workflow-create-version-label@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
