name: Issue Needs Attention
# This workflow is triggered on issue comments.
on:
  issue_comment:
    types: created

permissions:
  contents: read

jobs:
  applyNeedsAttentionLabel:
    permissions:
      contents: read  # for actions/checkout to fetch code
      issues: write  # for hramos/needs-attention to label issues
    name: Apply Needs Attention Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply Needs Attention Label
        uses: hramos/needs-attention@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          response-required-label: "Needs: Author Feedback"
          needs-attention-label: "Needs: Attention"
        id: needs-attention
      - name: Result
        run: echo '${{ steps.needs-attention.outputs.result }}'
