name: Test Docker Android Image
# This workflow is triggered on commits to main and pull requests.
on:
  push:
    branches:
      - main
  pull_request:
    types: [ synchronize ]
    branches:
      - main

jobs:
  test-docker-android:
    name: Test Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image with Android test app
        run: npm run docker-build-android
